version: "3"
services:
  frontend:
    container_name: tt_web
    image: tt_web_server
    build: ./web_server/
    ports:
      - "8069:8069"
    volumes:
      - "./web_server/src:/usr/bin/src/webapp/src"
    restart: unless-stopped
  backend:
    container_name: tt_api
    image: tt_api_server
    build: ./api_server/
    ports:
      - "8075:8075"
    volumes:
      - "./api_server:/api_server"
    restart: unless-stopped
