version: "3"
services:
  frontend:
    container_name: tt_web
    image: tt_web_server
    build: ./web_server/
    ports:
      - "8069:8069"
    volumes:
      - "./web_server/src:/usr/bin/src/webapp/src"
    restart: unless-stopped
  backend:
    container_name: test_api
    image: test_api_server
    build: ./test_api/
    ports:
      - "8011:8011"
    volumes:
      - "./test_api:/test_api"
    restart: unless-stopped
